import { AppThemeConfig, CoreAppThemeId, ThemeVariantTokens } from './types';

export const SIGNATURE_TOKENS: ThemeVariantTokens = {
  background: '#0B0D14',
  backgroundSecondary: '#0F121C',
  surface: '#141724',
  surfaceElevated: '#191E2E',
  surfaceHover: '#1E2336',
  textPrimary: '#F8FAFC',
  textSecondary: '#CBD5E1',
  textMuted: '#64748B',
  border: 'rgba(255, 255, 255, 0.08)',
  borderSubtle: 'rgba(255, 255, 255, 0.05)',
  borderFocus: '#6366F1',
  primary: '#6366F1',
  primaryHover: '#4F46E5',
  primaryText: '#FFFFFF',
  primaryGlow: 'rgba(99, 102, 241, 0.25)',
  secondary: '#1E2336',
  secondaryHover: '#262D44',
  secondaryText: '#F8FAFC',
  accent: '#6366F1',
  accentHover: '#4F46E5',
  accentText: '#FFFFFF',
  accentGlow: 'rgba(99, 102, 241, 0.20)',
  badgeBg: 'rgba(255, 255, 255, 0.06)',
  badgeText: '#E2E8F0',
  badgeBorder: 'rgba(255, 255, 255, 0.10)',
  cardBg: '#131724',
  cardBorder: 'rgba(255, 255, 255, 0.08)',
  cardShadow: '0 4px 24px -1px rgba(0, 0, 0, 0.40), 0 0 0 1px rgba(255, 255, 255, 0.05)',
  inputBg: '#0F121C',
  inputBorder: 'rgba(255, 255, 255, 0.12)',
  inputText: '#F8FAFC',
  buttonBg: '#6366F1',
  buttonText: '#FFFFFF',
  buttonHoverBg: '#4F46E5',
  navbarBg: 'rgba(11, 13, 20, 0.85)',
  navbarBorder: 'rgba(255, 255, 255, 0.08)',
  navActiveBg: 'rgba(99, 102, 241, 0.15)',
  navActiveText: '#818CF8',
  navInactiveText: '#94A3B8',
  navContainerBg: '#0F121C',
  navContainerBorder: 'rgba(255, 255, 255, 0.08)',
  success: '#10B981',
  warning: '#F59E0B',
  danger: '#EF4444',
  chartColors: ['#6366F1', '#38BDF8', '#10B981', '#F59E0B', '#A855F7'],
  heroGradient: 'from-[#6366F1] via-[#4F46E5] to-[#312E81]',
  activeTabGradient: 'from-[#6366F1] to-[#4F46E5]',
  buttonGradient: 'from-[#6366F1] to-[#4F46E5]'
};

export const SIGNATURE_THEME: AppThemeConfig = {
  id: 'professional',
  name: 'CareerCompass AI',
  subtitle: 'Linear Dark Monochrome',
  purpose: 'Refined typography, high contrast dark palette, and data-dense UI',
  categoryBadge: 'Default',
  fontDisplay: "'Plus Jakarta Sans', system-ui, sans-serif",
  fontBody: "'Plus Jakarta Sans', system-ui, sans-serif",
  cardRadius: '0.875rem',
  buttonRadius: '0.5rem',
  inputRadius: '0.5rem',
  borderWidth: '1px',
  buttonStyleType: 'corporate-saas',
  cardStyleType: 'corporate',
  visualAtmosphere: 'monochrome',
  decorativePattern: 'monochrome-minimal',
  previewDots: ['#0B0D14', '#141724', '#6366F1', '#F8FAFC'],
  light: SIGNATURE_TOKENS,
  dark: SIGNATURE_TOKENS,
  flavor: {
    platformTitle: 'CareerCompass AI',
    platformBadge: 'AI Career Intelligence',
    tagline: 'Precision AI Career Discovery & Roadmaps for University Students',
    discoverySectionTitle: 'Career Recommendations',
    assessmentSectionTitle: 'AI Career Assessment',
    roadmapSectionTitle: 'Career Roadmap',
    skillsSectionTitle: 'Skill Gap Analysis',
    resumeSectionTitle: 'Resume Analyzer',
    interviewSectionTitle: 'Interview Prep',
    facultySectionTitle: 'Faculty Dashboard'
  }
};

// All themes resolve to the single permanent signature theme
export const APP_THEMES_DATA: Record<CoreAppThemeId, AppThemeConfig> = {
  'professional': SIGNATURE_THEME,
  'ocean': { ...SIGNATURE_THEME, id: 'ocean' },
  'sunset': { ...SIGNATURE_THEME, id: 'sunset' },
  'forest': { ...SIGNATURE_THEME, id: 'forest' },
  'lavender': { ...SIGNATURE_THEME, id: 'lavender' },
  'monochrome': { ...SIGNATURE_THEME, id: 'monochrome' },
  'retro': { ...SIGNATURE_THEME, id: 'retro' },
  'cyberpunk': { ...SIGNATURE_THEME, id: 'cyberpunk' },
  'dark-academia': { ...SIGNATURE_THEME, id: 'dark-academia' },
  'candy': { ...SIGNATURE_THEME, id: 'candy' }
};
