import React, { useState } from 'react';
import { 
  Sparkles, 
  TrendingUp, 
  DollarSign, 
  CheckCircle2, 
  AlertCircle, 
  Briefcase, 
  ArrowRight, 
  Bookmark, 
  ChevronDown, 
  ChevronUp, 
  Building2,
  BookOpenCheck,
  ShieldCheck,
  Zap,
  Clock,
  Target,
  Award
} from 'lucide-react';
import { CareerRecommendation } from '../types';

interface CareerRecommendationsProps {
  recommendations: CareerRecommendation[];
  onSelectRoleForRoadmap: (roleTitle: string) => void;
  onSaveCareer: (career: CareerRecommendation) => void;
  savedTitles: string[];
  isGenerating: boolean;
  onGoToProfile: () => void;
}

export const CareerRecommendations: React.FC<CareerRecommendationsProps> = ({
  recommendations,
  onSelectRoleForRoadmap,
  onSaveCareer,
  savedTitles,
  isGenerating,
  onGoToProfile,
}) => {
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const toggleExpand = (id: string) => {
    setExpandedId(prev => (prev === id ? null : id));
  };

  if (isGenerating) {
    return (
      <div className="max-w-4xl mx-auto p-12 text-center rounded-3xl bg-slate-900/40 border border-slate-800 backdrop-blur-xl space-y-6 animate-pulse">
        <div className="w-16 h-16 mx-auto rounded-2xl bg-gradient-to-tr from-blue-600 via-indigo-600 to-purple-600 flex items-center justify-center text-white shadow-lg shadow-blue-500/20">
          <Sparkles className="w-8 h-8 animate-spin" />
        </div>
        <div className="space-y-2">
          <h3 className="text-xl font-bold text-slate-100">Gemini AI is Conducting Career Assessment...</h3>
          <p className="text-xs text-slate-400 max-w-md mx-auto leading-relaxed">
            Analyzing Academic Profile, Core Skills, Projects, Certifications, Interests, and Experience to generate your Top 5 Career Matches.
          </p>
        </div>
        <div className="w-full max-w-sm mx-auto h-1.5 rounded-full bg-slate-800 overflow-hidden">
          <div className="h-full bg-gradient-to-r from-blue-500 via-indigo-500 to-purple-500 animate-pulse w-3/4" />
        </div>
      </div>
    );
  }

  if (!recommendations || recommendations.length === 0) {
    return (
      <div className="max-w-3xl mx-auto p-10 text-center rounded-3xl bg-slate-900/40 border border-slate-800 backdrop-blur-xl space-y-6">
        <div className="w-16 h-16 mx-auto rounded-2xl bg-blue-500/10 border border-blue-500/20 flex items-center justify-center text-blue-400">
          <Briefcase className="w-8 h-8" />
        </div>
        <div>
          <h3 className="text-xl font-bold text-slate-100">No Career Assessment Available Yet</h3>
          <p className="text-xs text-slate-400 mt-2 max-w-md mx-auto leading-relaxed">
            Complete your student profile (academic, skills, projects, certifications) to trigger Gemini AI to analyze and generate your Top 5 matched careers.
          </p>
        </div>
        <button
          onClick={onGoToProfile}
          className="px-6 py-3 rounded-xl text-xs font-bold bg-gradient-to-r from-blue-600 to-indigo-600 text-white shadow-lg shadow-blue-900/20 hover:brightness-110 transition-all inline-flex items-center gap-2"
        >
          <Sparkles className="w-4 h-4" />
          <span>Build Your Student Profile</span>
        </button>
      </div>
    );
  }

  return (
    <div className="max-w-6xl mx-auto space-y-8 pb-12">
      
      {/* Banner */}
      <div className="text-center space-y-3">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-300 text-xs font-semibold">
          <Sparkles className="w-4 h-4 text-amber-400" />
          <span>AI Career Assessment — Top {recommendations.length} Recommendations</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-100 tracking-tight">
          Your Top 5 AI Career Assessments
        </h1>
        <p className="text-sm text-slate-400 max-w-2xl mx-auto">
          Generated by Gemini AI by evaluating your academic performance, skill stack, projects, certifications, interests, and career goals.
        </p>
      </div>

      {/* Cards List */}
      <div className="space-y-8">
        {recommendations.slice(0, 5).map((role, rankIndex) => {
          const isSaved = savedTitles.includes(role.title);
          const isExpanded = expandedId === role.id;

          // Missing skills array fallback
          const missingSkillsList = role.missingSkills || role.skillsGap?.map(g => g.skill) || [];
          const strengthsList = role.strengths || role.matchingSkills || [];
          const weaknessesList = role.weaknesses || [];

          return (
            <div
              key={role.id || rankIndex}
              className="group relative p-6 sm:p-8 rounded-3xl bg-slate-900/50 border border-slate-800 hover:border-slate-700/80 backdrop-blur-xl shadow-2xl transition-all duration-300"
            >
              {/* Subtle radial light background effect */}
              <div className="absolute -right-10 -top-10 w-48 h-48 bg-blue-500/5 blur-[90px] pointer-events-none" />

              {/* Top Banner Row */}
              <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-6 pb-6 border-b border-slate-800/80">
                
                {/* Rank & Title & Match Score */}
                <div className="flex items-start gap-4">
                  
                  {/* Rank Badge */}
                  <div className="flex items-center justify-center w-8 h-8 rounded-xl bg-blue-500/10 border border-blue-500/30 text-blue-400 font-bold text-xs shrink-0 mt-1">
                    #{rankIndex + 1}
                  </div>

                  {/* Career Match % Circle / Gauge */}
                  <div className="relative flex flex-col items-center justify-center w-16 h-16 rounded-2xl bg-slate-950/90 border border-slate-800 text-slate-100 shadow-lg shrink-0">
                    <span className="text-2xl font-black text-emerald-400 tracking-tight">{role.matchScore}%</span>
                    <span className="text-[9px] font-extrabold text-slate-400 uppercase tracking-widest">Match</span>
                  </div>

                  <div>
                    <div className="flex flex-wrap items-center gap-2.5 mb-1.5">
                      <h2 className="text-xl sm:text-2xl font-bold text-slate-100 tracking-tight">
                        {role.title}
                      </h2>
                      <span className="px-3 py-0.5 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 text-xs font-semibold flex items-center gap-1">
                        <TrendingUp className="w-3.5 h-3.5" />
                        <span>Growth: {role.demandGrowth}</span>
                      </span>
                    </div>

                    {/* Reason / Short Summary */}
                    <p className="text-xs text-slate-300 leading-relaxed max-w-2xl mt-1">
                      <strong className="text-blue-300">Match Rationale: </strong>
                      {role.reason || role.shortSummary || role.aiReasoning}
                    </p>
                  </div>
                </div>

                {/* Salary & Actions */}
                <div className="flex flex-wrap items-center gap-3 w-full lg:w-auto justify-between lg:justify-end">
                  
                  {/* Expected Salary Card */}
                  <div className="text-left lg:text-right px-4 py-2.5 rounded-2xl bg-slate-950/80 border border-slate-800 shrink-0">
                    <span className="text-[10px] uppercase tracking-wider font-extrabold text-slate-400 flex items-center gap-1">
                      <DollarSign className="w-3 h-3 text-emerald-400" />
                      Expected Salary
                    </span>
                    <span className="text-xs font-bold text-emerald-300 block mt-0.5">
                      {role.salaryRange.entry} <span className="text-[10px] text-slate-400 font-normal">(Entry)</span>
                    </span>
                  </div>

                  {/* Bookmark Button */}
                  <button
                    onClick={() => onSaveCareer(role)}
                    className={`p-3 rounded-2xl border text-xs font-semibold transition-all ${
                      isSaved
                        ? 'bg-purple-600 text-white border-purple-500 shadow-lg shadow-purple-900/30'
                        : 'bg-slate-800/60 hover:bg-slate-800 text-slate-300 border-slate-700/60'
                    }`}
                    title={isSaved ? 'Saved in Firebase' : 'Save Career Path'}
                  >
                    <Bookmark className={`w-4 h-4 ${isSaved ? 'fill-current' : ''}`} />
                  </button>

                  {/* Roadmap Button */}
                  <button
                    onClick={() => onSelectRoleForRoadmap(role.title)}
                    className="px-5 py-3 rounded-2xl text-xs font-bold bg-gradient-to-r from-blue-600 via-indigo-600 to-purple-600 text-white shadow-lg shadow-blue-900/20 hover:brightness-110 active:scale-95 transition-all flex items-center gap-2"
                  >
                    <span>Create Roadmap</span>
                    <ArrowRight className="w-4 h-4" />
                  </button>
                </div>
              </div>

              {/* Assessment Grid: Strengths, Weaknesses & Missing Skills */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-5 pt-6">
                
                {/* 1. Strengths */}
                <div className="p-4 rounded-2xl bg-slate-950/50 border border-emerald-500/15 space-y-2">
                  <h4 className="text-xs font-extrabold text-emerald-400 uppercase tracking-wider flex items-center gap-1.5">
                    <ShieldCheck className="w-4 h-4 text-emerald-400" />
                    <span>Candidate Strengths ({strengthsList.length})</span>
                  </h4>
                  <ul className="space-y-1.5 text-xs text-slate-300">
                    {strengthsList.slice(0, 3).map((st, idx) => (
                      <li key={idx} className="flex items-start gap-1.5">
                        <span className="text-emerald-400 font-bold shrink-0">✓</span>
                        <span className="line-clamp-2">{st}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                {/* 2. Weaknesses */}
                <div className="p-4 rounded-2xl bg-slate-950/50 border border-amber-500/15 space-y-2">
                  <h4 className="text-xs font-extrabold text-amber-400 uppercase tracking-wider flex items-center gap-1.5">
                    <AlertCircle className="w-4 h-4 text-amber-400" />
                    <span>Areas to Develop</span>
                  </h4>
                  {weaknessesList.length > 0 ? (
                    <ul className="space-y-1.5 text-xs text-slate-300">
                      {weaknessesList.slice(0, 3).map((wk, idx) => (
                        <li key={idx} className="flex items-start gap-1.5">
                          <span className="text-amber-400 font-bold shrink-0">•</span>
                          <span className="line-clamp-2">{wk}</span>
                        </li>
                      ))}
                    </ul>
                  ) : (
                    <p className="text-xs text-slate-400 italic">
                      No critical weaknesses identified. Minor practical cloud experience recommended.
                    </p>
                  )}
                </div>

                {/* 3. Missing Skills */}
                <div className="p-4 rounded-2xl bg-slate-950/50 border border-rose-500/15 space-y-2">
                  <h4 className="text-xs font-extrabold text-rose-400 uppercase tracking-wider flex items-center gap-1.5">
                    <Target className="w-4 h-4 text-rose-400" />
                    <span>Missing Skills to Bridge</span>
                  </h4>
                  <div className="flex flex-wrap gap-1.5">
                    {missingSkillsList.map((mSk, idx) => (
                      <span
                        key={idx}
                        className="px-2.5 py-1 rounded-lg bg-rose-500/10 border border-rose-500/20 text-rose-300 text-[11px] font-semibold"
                      >
                        ! {mSk}
                      </span>
                    ))}
                  </div>
                </div>

              </div>

              {/* Future Demand & Expand Footer */}
              <div className="mt-6 pt-4 border-t border-slate-800/80 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                
                {/* Future Demand Note */}
                <div className="flex items-center gap-2 text-xs text-slate-400 max-w-xl">
                  <Zap className="w-4 h-4 text-amber-400 shrink-0" />
                  <span>
                    <strong className="text-slate-200">Future Demand & Outlook: </strong>
                    {role.futureDemand || `${role.demandGrowth} projected over next 5 years with strong industry hiring momentum.`}
                  </span>
                </div>

                {/* Toggle Button */}
                <button
                  onClick={() => toggleExpand(role.id)}
                  className="text-xs font-bold text-indigo-400 hover:text-indigo-300 flex items-center gap-1 transition-colors shrink-0"
                >
                  <span>{isExpanded ? 'Hide Assessment Details' : 'View Full Assessment & Day-in-Life'}</span>
                  {isExpanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                </button>
              </div>

              {/* Collapsible Deep Details */}
              {isExpanded && (
                <div className="mt-6 p-6 rounded-2xl bg-slate-950/80 border border-indigo-500/20 space-y-6 animate-fade-in">
                  
                  {/* Comprehensive Salary Breakdown */}
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 p-4 rounded-xl bg-slate-900/80 border border-slate-800">
                    <div className="text-center sm:text-left">
                      <span className="text-[10px] font-bold text-slate-500 uppercase block">Entry-Level Salary</span>
                      <span className="text-sm font-extrabold text-emerald-300">{role.salaryRange.entry}</span>
                    </div>
                    <div className="text-center sm:text-left">
                      <span className="text-[10px] font-bold text-slate-500 uppercase block">Mid-Level Salary</span>
                      <span className="text-sm font-extrabold text-blue-300">{role.salaryRange.mid}</span>
                    </div>
                    <div className="text-center sm:text-left">
                      <span className="text-[10px] font-bold text-slate-500 uppercase block">Senior-Level Salary</span>
                      <span className="text-sm font-extrabold text-purple-300">{role.salaryRange.senior || '$180,000+'}</span>
                    </div>
                  </div>

                  {/* Day in Life */}
                  <div>
                    <h5 className="text-xs font-bold text-indigo-300 uppercase tracking-wider mb-1 flex items-center gap-1.5">
                      <Briefcase className="w-4 h-4" />
                      Day-in-the-Life Summary
                    </h5>
                    <p className="text-xs text-slate-300 leading-relaxed bg-slate-900/60 p-4 rounded-xl border border-slate-800/60">
                      {role.dayInLife}
                    </p>
                  </div>

                  {/* Top Hiring Employers */}
                  <div>
                    <h5 className="text-xs font-bold text-slate-300 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                      <Building2 className="w-4 h-4 text-indigo-400" />
                      Top Target Employers Hiring for this Role
                    </h5>
                    <div className="flex flex-wrap gap-2">
                      {(role.topEmployers || ['Google', 'Microsoft', 'Stripe', 'Amazon']).map((emp, idx) => (
                        <span key={idx} className="px-3 py-1 rounded-xl bg-slate-900 border border-slate-800 text-xs font-medium text-slate-200">
                          🏢 {emp}
                        </span>
                      ))}
                    </div>
                  </div>

                  {/* Skill Gap Learning Plan */}
                  {role.skillsGap && role.skillsGap.length > 0 && (
                    <div>
                      <h5 className="text-xs font-bold text-amber-300 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                        <BookOpenCheck className="w-4 h-4" />
                        Recommended Action Plan to Acquire Missing Skills:
                      </h5>
                      <div className="space-y-2">
                        {role.skillsGap.map((gap, idx) => (
                          <div key={idx} className="p-3.5 rounded-xl bg-slate-900 border border-slate-800 text-xs flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                            <div>
                              <span className="font-bold text-amber-300">{gap.skill} </span>
                              <span className="text-[10px] px-2 py-0.5 rounded bg-amber-500/10 text-amber-400 font-semibold ml-1">
                                {gap.importance} Priority
                              </span>
                              <p className="text-slate-300 mt-1">{gap.howToAcquire || 'Take an industry certified online module and build a portfolio project.'}</p>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* CTA */}
                  <div className="pt-2 flex justify-end">
                    <button
                      onClick={() => onSelectRoleForRoadmap(role.title)}
                      className="px-6 py-3 rounded-xl text-xs font-bold bg-indigo-600 hover:bg-indigo-500 text-white shadow-lg transition-all flex items-center gap-2"
                    >
                      <Sparkles className="w-4 h-4" />
                      <span>Generate Personal Skill Roadmap for {role.title}</span>
                    </button>
                  </div>

                </div>
              )}

            </div>
          );
        })}
      </div>

    </div>
  );
};

